#!/bin/bash

# Set start time of script
start_time=$(date +"%H:%M:%S")

# Declare opts variable
skips=()

# Function for opt arguments passed with command
containsElement() {
    local element match="$1"
    shift
    for element; do [[ "$element" == "$match" ]] && return 0; done
    return 1
}

# Process options
while getopts "s:" opt; do
    case $opt in
        s)
            skips+=("$OPTARG")
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

# Shift the processed options away
shift $((OPTIND-1))

# Validate sudo credentials
sudo -v

# Declare logfile variables
log_dir="$HOME/log/updateall"
log_file="${log_dir}/updateall-$(date +"%Y%m%d-%H%M%S").log"

# Check for log directory existance and create if it does not
if [ ! -d "$log_dir" ]; then
    mkdir -p "$log_dir"
fi

# Color codes for terminal output
RED='\033[1;38;5;1m'
GREEN='\033[1;38;5;2m'
YELLOW='\033[1;38;5;3m'
BLUE='\033[1;38;5;4m'
RESET='\033[0m'

# Define log function
log() {
    echo -e "${YELLOW}$(date +"%Y-%m-%d %H:%M:%S")${RESET} $1" >> "$log_file"
}

# Define spacing function for formatting in logfile
log_space() {
    for i in {1..3}; do
        echo "" >> "$log_file"
    done
}

# Define spacing function for formatting in logfile
log_line() {
    echo "" >> "$log_file"
}

# Function to update oh-my-posh
updateomp() {
    # Set function variables
    currentVersion=$(oh-my-posh --version)
    errorOutput=$(mktemp)
    originLoc="https://ohmyposh.dev/install.sh"
    destFile="$HOME/.local/bin"
    message="\nTheme files have been reinstalled and custom themes added to themes folder.\nRun \e[1;38;5;10mompsel\e[0m for theme selection."

    # Function to remove temporary files
    cleanup() {
        rm -f "$errorOutput"
    }

    # Enable exit on termination of script
    trap cleanup EXIT

    # Send info to user
    echo "Checking updates for Oh My Posh."

    # Retrieve installation script and run
    log "Starting script download and execution."
    curl -s "$originLoc" | bash -s -- -d "$destFile" > /dev/null 2> "$errorOutput"
    log "Script download and execution complete."

    # Error handling with output to user
    if [[ $? -eq 0 ]]; then
        newVersion="$(oh-my-posh --version)"
        if [[ "$currentVersion" == "$newVersion" ]]; then
            echo -e "Oh My Posh \e[1;38;5;10m${currentVersion}\033[0m is already up to date.${message}"
            log "Version checked; ${currentVersion} is current version."
        else
            echo -e "Oh My Posh has been updated from \033[1;38;5;1m${currentVersion}\033[0m to \033[1;38;5;10m${newVersion}\033[0m.${message}"
            log "Oh My Posh updated from ${currentVersion} to ${newVersion}."
        fi
    else
        echo -e "\033[1;38;5;1mFailed\033[0m to update Oh My Posh:"
        cat $errorOutput
        log "Update failed: $(cat "$errorOutput")"
    fi

    # Copy custom themes into themes directory (gets overwritten with every update).
    if [ -d "$HOME/.cache/oh-my-posh/custom_themes" ]; then
        cp $HOME/.cache/oh-my-posh/custom_themes/* $HOME/.cache/oh-my-posh/themes/ && log "Custom themes added to themes folder."
    else
        echo "No custom themes detected. Create custom themes and add to\n $HOME/.cache/oh-my-posh/custom_themes to include in ompsel themes list."
    fi

   rm -rf $HOME/.cache/oh-my-posh/themes/*.bak
}



# Log beginning of script
log "Updateall started"

# Array of package managers
pkgmgr=('omposh' 'apt' 'snap' 'flatpak' 'deb-get' 'pipx' 'pacman' 'zypper' 'dnf' 'yay')

# Function to check if a package manager is installed
check_package_manager() {
    if [ "$1" == omposh ]; then
        command -v oh-my-posh >/dev/null 2>&1
    else
        command -v "$1" >/dev/null 2>&1
    fi
}

# Array to store the results of each package manager update
results=()

# Loop through each package manager
for item in "${pkgmgr[@]}"; do
item_formatted=$(echo -e ${BLUE}${item}${RESET})
log_space
log "STARTING UPDATE FOR: ${item}"
log_line
log "Checking for presence of package manager: ${item_formatted}."

    # Check if the package manager is installed
    if check_package_manager "$item"; then
        log "Package manager ${item_formatted} found."
        printf "${GREEN}%-3s ${YELLOW}%-8s ${RED}%7s ${GREEN}%s${RESET}\n" "❱❱❱" "UPDATING" "$(echo ${item} | tr '[:lower:]' '[:upper:]')" "❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰❰"

        # Update package manager based on type
        case "$item" in
            "apt")
                if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    sudo apt-get update && sudo apt-get upgrade 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "snap")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    sudo snap refresh 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "flatpak")
                if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    if [ -n "$SSH_CONNECTION" ]; then
                        echo -e "${YELLOW}Skipping:${RED} $(echo ${item} | tr '[:lower:]' '[:upper:]')${RESET}: running through ssh"
                        log "SSH connection detected; skipping ${item} package manager update."
                        [[ -z "$SSH_CONNECTION" ]]
                    else
                        log "Running ${item_formatted} package manager update."
                        log "OUTPUT:"
                        flatpak update -y 2>&1 | tee -a "$log_file"
                        log "Update for ${item_formatted} package manager complete."
                    fi
                fi
                ;;
            "deb-get")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    deb-get update && deb-get upgrade 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "pipx")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    pipx upgrade-all 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "pacman")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    sudo pacman -Syu 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "zypper")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    sudo zypper refresh && sudo zypper update 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "dnf")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    sudo dnf check-update && sudo dnf upgrade 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
            "yay")
                 if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} package manager update."
                    log "OUTPUT:"
                    yay -Syu 2>&1 | tee -a "$log_file"
                    log "Update for ${item_formatted} package manager complete."
                fi
                ;;
           "omposh")
                if containsElement "$item" "${skips[@]}"; then
                    echo "Skip flag detected:"
                    log "Skipping update for ${item} per user command argument."
                else
                    log "Running ${item_formatted} update."
                    log "OUTPUT:"
                    updateomp
                    log "Update for ${item_formatted} complete."
                fi
                ;;
            *)
                echo "Unknown package manager: $item"
                ;;
        esac

        # Check if the previous command succeeded
        if [ $? -eq 0 ]; then
            if containsElement "$item" "${skips[@]}"; then
                echo -e "${YELLOW}●${RESET} $(echo ${item} | tr '[:lower:]' '[:upper:]') packages skipped per user input"
                result_msg=$(printf "${BLUE}%-8s${RESET} %-20s ${YELLOW}%-10s${RESET}\n" "$(echo " ${item}" | tr '[:lower:]' '[:upper:]')" "package update status:" "user-skip")
            else
                echo -e "${GREEN} ●${RESET} $(echo ${item} | tr '[:lower:]' '[:upper:]') packages updated successfully"
                if command -v notify-send >/dev/null 2>&1; then
                    notify-send --app-name="Package Update Results" --icon=emblem-success "$(echo ${item} | tr '[:lower:]' '[:upper:]') packages updated successfully"
                fi
                result_msg=$(printf "${BLUE}%-8s${RESET} %-20s ${GREEN}%-10s${RESET}\n" "$(echo " ${item}" | tr '[:lower:]' '[:upper:]')" "package update status:" "succeeded")
            fi
            log "$result_msg"
        else
            echo -e "${RED} ●${RESET} Failed to update $(echo ${item} | tr '[:lower:]' '[:upper:]') packages"
            if command -v notify-send >/dev/null 2>&1; then
                notify-send --app-name="Package Update Results" --icon=emblem-unreadable "$(echo ${item} | tr '[:lower:]' '[:upper:]') packages failed to update"
            fi
            result_msg=$(printf "${BLUE}%-8s${RESET} %-20s ${RED}%-10s${RESET}\n" "$(echo " ${item}" | tr '[:lower:]' '[:upper:]')" "package update status:" "failed")
            log "$result_msg"
        fi
            results+=("$result_msg")
    else
        skippedpackage=$(echo ${item} | tr '[:lower:]' '[:upper:]')
        printf "${YELLOW}%-9s${RESET} ${RED}%-8s${RESET} %s\n" "Skipping: " "${skippedpackage}" " is not installed."
        log "Skipping ${item} package manager update; ${item} not installed."
        result_msg=$(printf "${BLUE}%-8s${RESET} %-20s ${YELLOW}%-10s${RESET}\n" "$(echo " ${item}" | tr '[:lower:]' '[:upper:]')" "package update status:" "skipped")
#        results+=("$result_msg") # uncomment to enable skipping results in summary table
    fi

done

end_time=$(date +"%H:%M:%S")

time_to_seconds() {
    local time_str=$1
    local hours=${time_str%%:*}
    local minutes=${time_str#*:}
    minutes=${minutes%%:*}
    local seconds=${time_str##*:}

    hours=${hours#0}
    minutes=${minutes#0}
    seconds=${seconds#0}

    echo $((hours * 3600 + minutes * 60 + seconds))
}

start_seconds=$(time_to_seconds "$start_time")
end_seconds=$(time_to_seconds "$end_time")

seconds_diff=$((end_seconds - start_seconds))

echo ""
# echo ""
formatted_stime=$(printf "%-15s ${YELLOW}%s${RESET}\n" "started at:" "${start_time}")
formatted_etime=$(printf "%-15s ${GREEN}%s${RESET}\n" "completed at:" "${end_time}")
# echo "┌────────────────────────┐"
# echo "│    Script Run Time     │"
# echo "├────────────────────────┤"
# echo "│$formatted_stime│"
# echo "│$formatted_etime│"
# echo "└────────────────────────┘"
# echo ""
echo -e "Script runtime: ${YELLOW}${seconds_diff}${RESET} seconds."
echo ""
echo "Summary results below:"
echo ""

# Print summary results
log_space
echo "┌──────────────────────────────────────────┐" | tee -a "$log_file"
echo "│          Package Update Summary          │" | tee -a "$log_file"
echo "├──────────────────────────────────────────┤" | tee -a "$log_file"
for result in "${results[@]}"; do
echo "│$result│" | tee -a "$log_file"
done
echo "└──────────────────────────────────────────┘" | tee -a "$log_file"

log "Updateall complete"
